peripheral: GLOBAL_CCM00_NS
version: 0.1.0
registers:
- id: TASKS_START
  address_offset: 0
  size: 32
  access: WRITE_ONLY
  reset_value: 0
  fields:
  - name: TASKS_START
    bit_range:
    - 0
    - 0
    description: Start encryption/decryption. This operation will stop by itself when completed.
  side_effects: null
- id: TASKS_STOP
  address_offset: 4
  size: 32
  access: WRITE_ONLY
  reset_value: 0
  fields:
  - name: TASKS_STOP
    bit_range:
    - 0
    - 0
    description: Stop encryption/decryption
  side_effects: null
- id: TASKS_RATEOVERRIDE
  address_offset: 8
  size: 32
  access: WRITE_ONLY
  reset_value: 0
  fields:
  - name: TASKS_RATEOVERRIDE
    bit_range:
    - 0
    - 0
    description: Override DATARATE setting in MODE register with the contents of the RATEOVERRIDE register for any ongoing encryption/decryption
  side_effects: null
- id: SUBSCRIBE_START
  address_offset: 128
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: CHIDX
    bit_range:
    - 7
    - 0
    description: DPPI channel that task START will subscribe to
  - name: EN
    bit_range:
    - 31
    - 31
  side_effects: null
- id: SUBSCRIBE_STOP
  address_offset: 132
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: CHIDX
    bit_range:
    - 7
    - 0
    description: DPPI channel that task STOP will subscribe to
  - name: EN
    bit_range:
    - 31
    - 31
  side_effects: null
- id: SUBSCRIBE_RATEOVERRIDE
  address_offset: 136
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: CHIDX
    bit_range:
    - 7
    - 0
    description: DPPI channel that task RATEOVERRIDE will subscribe to
  - name: EN
    bit_range:
    - 31
    - 31
  side_effects: null
- id: EVENTS_END
  address_offset: 260
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: EVENTS_END
    bit_range:
    - 0
    - 0
    description: Encrypt/decrypt complete or ended because of an error
  side_effects: null
- id: EVENTS_ERROR
  address_offset: 264
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: EVENTS_ERROR
    bit_range:
    - 0
    - 0
    description: CCM error event
  side_effects: null
- id: PUBLISH_END
  address_offset: 388
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: CHIDX
    bit_range:
    - 7
    - 0
    description: DPPI channel that event END will publish to
  - name: EN
    bit_range:
    - 31
    - 31
  side_effects: null
- id: PUBLISH_ERROR
  address_offset: 392
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: CHIDX
    bit_range:
    - 7
    - 0
    description: DPPI channel that event ERROR will publish to
  - name: EN
    bit_range:
    - 31
    - 31
  side_effects: null
- id: INTENSET
  address_offset: 772
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: END
    bit_range:
    - 1
    - 1
    description: Write '1' to enable interrupt for event END
  - name: ERROR
    bit_range:
    - 2
    - 2
    description: Write '1' to enable interrupt for event ERROR
  side_effects: null
- id: INTENCLR
  address_offset: 776
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: END
    bit_range:
    - 1
    - 1
    description: Write '1' to disable interrupt for event END
  - name: ERROR
    bit_range:
    - 2
    - 2
    description: Write '1' to disable interrupt for event ERROR
  side_effects: null
- id: MACSTATUS
  address_offset: 1024
  size: 32
  access: READ_ONLY
  reset_value: 0
  fields:
  - name: MACSTATUS
    bit_range:
    - 0
    - 0
    description: The result of the MAC check performed during the previous decryption operation
  side_effects: null
- id: ERRORSTATUS
  address_offset: 1028
  size: 32
  access: READ_ONLY
  reset_value: 0
  fields:
  - name: ERRORSTATUS
    bit_range:
    - 2
    - 0
    description: Error status when the ERROR event is generated
  side_effects: null
- id: ENABLE
  address_offset: 1280
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: ENABLE
    bit_range:
    - 1
    - 0
    description: Enable or disable CCM
  side_effects: null
- id: MODE
  address_offset: 1284
  size: 32
  access: READ_WRITE
  reset_value: 1
  fields:
  - name: MODE
    bit_range:
    - 1
    - 0
    description: The mode of operation to be used. The settings in this register apply when the CRYPT task is triggered.
  - name: PROTOCOL
    bit_range:
    - 9
    - 8
    description: Protocol and packet format selection
  - name: DATARATE
    bit_range:
    - 18
    - 16
    description: Radio data rate that the CCM shall run synchronous with
  - name: MACLEN
    bit_range:
    - 26
    - 24
    description: CCM MAC length (bytes)
  side_effects: null
- id: KEY_VALUE0
  address_offset: 1296
  size: 32
  access: WRITE_ONLY
  reset_value: 0
  fields:
  - name: VALUE
    bit_range:
    - 31
    - 0
    description: 'AES 128-bit key value, bits (32*(i+1))-1 : (32*i)'
  side_effects: null
- id: KEY_VALUE1
  address_offset: 1300
  size: 32
  access: WRITE_ONLY
  reset_value: 0
  fields:
  - name: VALUE
    bit_range:
    - 31
    - 0
    description: 'AES 128-bit key value, bits (32*(i+1))-1 : (32*i)'
  side_effects: null
- id: KEY_VALUE2
  address_offset: 1304
  size: 32
  access: WRITE_ONLY
  reset_value: 0
  fields:
  - name: VALUE
    bit_range:
    - 31
    - 0
    description: 'AES 128-bit key value, bits (32*(i+1))-1 : (32*i)'
  side_effects: null
- id: KEY_VALUE3
  address_offset: 1308
  size: 32
  access: WRITE_ONLY
  reset_value: 0
  fields:
  - name: VALUE
    bit_range:
    - 31
    - 0
    description: 'AES 128-bit key value, bits (32*(i+1))-1 : (32*i)'
  side_effects: null
- id: NONCE_VALUE0
  address_offset: 1312
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: VALUE
    bit_range:
    - 31
    - 0
    description: 'NONCE value, bits (32*(n+1))-1 : (32*n)'
  side_effects: null
- id: NONCE_VALUE1
  address_offset: 1316
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: VALUE
    bit_range:
    - 31
    - 0
    description: 'NONCE value, bits (32*(n+1))-1 : (32*n)'
  side_effects: null
- id: NONCE_VALUE2
  address_offset: 1320
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: VALUE
    bit_range:
    - 31
    - 0
    description: 'NONCE value, bits (32*(n+1))-1 : (32*n)'
  side_effects: null
- id: NONCE_VALUE3
  address_offset: 1324
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: VALUE
    bit_range:
    - 31
    - 0
    description: 'NONCE value, bits (32*(n+1))-1 : (32*n)'
  side_effects: null
- id: IN_PTR
  address_offset: 1328
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: PTR
    bit_range:
    - 31
    - 0
    description: Input pointer
  side_effects: null
- id: OUT_PTR
  address_offset: 1336
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: PTR
    bit_range:
    - 31
    - 0
    description: Output pointer
  side_effects: null
- id: RATEOVERRIDE
  address_offset: 1348
  size: 32
  access: READ_WRITE
  reset_value: 2
  fields:
  - name: RATEOVERRIDE
    bit_range:
    - 2
    - 0
    description: Data rate override setting.
  side_effects: null
- id: ADATAMASK
  address_offset: 1352
  size: 32
  access: READ_WRITE
  reset_value: 227
  fields:
  - name: ADATAMASK
    bit_range:
    - 7
    - 0
    description: CCM adata mask.
  side_effects: null
interrupts:
  AAR00_CCM00: 70
timing: null
