peripheral: RTC
version: 0.1.0
registers:
- id: TR
  address_offset: 0
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: PM
    bit_range:
    - 22
    - 22
    description: AM/PM notation
  - name: HT
    bit_range:
    - 21
    - 20
    description: Hour tens in BCD format
  - name: HU
    bit_range:
    - 19
    - 16
    description: Hour units in BCD format
  - name: MNT
    bit_range:
    - 14
    - 12
    description: Minute tens in BCD format
  - name: MNU
    bit_range:
    - 11
    - 8
    description: Minute units in BCD format
  - name: ST
    bit_range:
    - 6
    - 4
    description: Second tens in BCD format
  - name: SU
    bit_range:
    - 3
    - 0
    description: Second units in BCD format
  side_effects: null
- id: DR
  address_offset: 4
  size: 32
  access: READ_WRITE
  reset_value: 8449
  fields:
  - name: YT
    bit_range:
    - 23
    - 20
    description: Year tens in BCD format
  - name: YU
    bit_range:
    - 19
    - 16
    description: Year units in BCD format
  - name: WDU
    bit_range:
    - 15
    - 13
    description: Week day units
  - name: MT
    bit_range:
    - 12
    - 12
    description: Month tens in BCD format
  - name: MU
    bit_range:
    - 11
    - 8
    description: Month units in BCD format
  - name: DT
    bit_range:
    - 5
    - 4
    description: Date tens in BCD format
  - name: DU
    bit_range:
    - 3
    - 0
    description: Date units in BCD format
  side_effects: null
- id: CR
  address_offset: 8
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: COE
    bit_range:
    - 23
    - 23
    description: Calibration output enable
  - name: OSEL
    bit_range:
    - 22
    - 21
    description: Output selection
  - name: POL
    bit_range:
    - 20
    - 20
    description: Output polarity
  - name: COSEL
    bit_range:
    - 19
    - 19
    description: Calibration Output selection
  - name: BKP
    bit_range:
    - 18
    - 18
    description: Backup
  - name: SUB1H
    bit_range:
    - 17
    - 17
    description: Subtract 1 hour (winter time change)
  - name: ADD1H
    bit_range:
    - 16
    - 16
    description: Add 1 hour (summer time change)
  - name: TSIE
    bit_range:
    - 15
    - 15
    description: Time-stamp interrupt enable
  - name: WUTIE
    bit_range:
    - 14
    - 14
    description: Wakeup timer interrupt enable
  - name: ALRBIE
    bit_range:
    - 13
    - 13
    description: Alarm B interrupt enable
  - name: ALRAIE
    bit_range:
    - 12
    - 12
    description: Alarm A interrupt enable
  - name: TSE
    bit_range:
    - 11
    - 11
    description: Time stamp enable
  - name: WUTE
    bit_range:
    - 10
    - 10
    description: Wakeup timer enable
  - name: ALRBE
    bit_range:
    - 9
    - 9
    description: Alarm B enable
  - name: ALRAE
    bit_range:
    - 8
    - 8
    description: Alarm A enable
  - name: DCE
    bit_range:
    - 7
    - 7
    description: Coarse digital calibration enable
  - name: FMT
    bit_range:
    - 6
    - 6
    description: Hour format
  - name: BYPSHAD
    bit_range:
    - 5
    - 5
    description: Bypass the shadow registers
  - name: REFCKON
    bit_range:
    - 4
    - 4
    description: Reference clock detection enable (50 or 60 Hz)
  - name: TSEDGE
    bit_range:
    - 3
    - 3
    description: Time-stamp event active edge
  - name: WCKSEL
    bit_range:
    - 2
    - 0
    description: Wakeup clock selection
  side_effects: null
- id: ISR
  address_offset: 12
  size: 32
  access: READ_WRITE
  reset_value: 7
  fields:
  - name: ALRAWF
    bit_range:
    - 0
    - 0
    description: Alarm A write flag
  - name: ALRBWF
    bit_range:
    - 1
    - 1
    description: Alarm B write flag
  - name: WUTWF
    bit_range:
    - 2
    - 2
    description: Wakeup timer write flag
  - name: SHPF
    bit_range:
    - 3
    - 3
    description: Shift operation pending
  - name: INITS
    bit_range:
    - 4
    - 4
    description: Initialization status flag
  - name: RSF
    bit_range:
    - 5
    - 5
    description: Registers synchronization flag
  - name: INITF
    bit_range:
    - 6
    - 6
    description: Initialization flag
  - name: INIT
    bit_range:
    - 7
    - 7
    description: Initialization mode
  - name: ALRAF
    bit_range:
    - 8
    - 8
    description: Alarm A flag
  - name: ALRBF
    bit_range:
    - 9
    - 9
    description: Alarm B flag
  - name: WUTF
    bit_range:
    - 10
    - 10
    description: Wakeup timer flag
  - name: TSF
    bit_range:
    - 11
    - 11
    description: Time-stamp flag
  - name: TSOVF
    bit_range:
    - 12
    - 12
    description: Time-stamp overflow flag
  - name: TAMP1F
    bit_range:
    - 13
    - 13
    description: Tamper detection flag
  - name: TAMP2F
    bit_range:
    - 14
    - 14
    description: TAMPER2 detection flag
  - name: RECALPF
    bit_range:
    - 16
    - 16
    description: Recalibration pending Flag
  side_effects: null
- id: PRER
  address_offset: 16
  size: 32
  access: READ_WRITE
  reset_value: 8323327
  fields:
  - name: PREDIV_A
    bit_range:
    - 22
    - 16
    description: Asynchronous prescaler factor
  - name: PREDIV_S
    bit_range:
    - 14
    - 0
    description: Synchronous prescaler factor
  side_effects: null
- id: WUTR
  address_offset: 20
  size: 32
  access: READ_WRITE
  reset_value: 65535
  fields:
  - name: WUT
    bit_range:
    - 15
    - 0
    description: Wakeup auto-reload value bits
  side_effects: null
- id: CALIBR
  address_offset: 24
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: DCS
    bit_range:
    - 7
    - 7
    description: Digital calibration sign
  - name: DC
    bit_range:
    - 4
    - 0
    description: Digital calibration
  side_effects: null
- id: ALRMAR
  address_offset: 28
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: MSK4
    bit_range:
    - 31
    - 31
    description: Alarm A date mask
  - name: WDSEL
    bit_range:
    - 30
    - 30
    description: Week day selection
  - name: DT
    bit_range:
    - 29
    - 28
    description: Date tens in BCD format
  - name: DU
    bit_range:
    - 27
    - 24
    description: Date units or day in BCD format
  - name: MSK3
    bit_range:
    - 23
    - 23
    description: Alarm A hours mask
  - name: PM
    bit_range:
    - 22
    - 22
    description: AM/PM notation
  - name: HT
    bit_range:
    - 21
    - 20
    description: Hour tens in BCD format
  - name: HU
    bit_range:
    - 19
    - 16
    description: Hour units in BCD format
  - name: MSK2
    bit_range:
    - 15
    - 15
    description: Alarm A minutes mask
  - name: MNT
    bit_range:
    - 14
    - 12
    description: Minute tens in BCD format
  - name: MNU
    bit_range:
    - 11
    - 8
    description: Minute units in BCD format
  - name: MSK1
    bit_range:
    - 7
    - 7
    description: Alarm A seconds mask
  - name: ST
    bit_range:
    - 6
    - 4
    description: Second tens in BCD format
  - name: SU
    bit_range:
    - 3
    - 0
    description: Second units in BCD format
  side_effects: null
- id: ALRMBR
  address_offset: 32
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: MSK4
    bit_range:
    - 31
    - 31
    description: Alarm B date mask
  - name: WDSEL
    bit_range:
    - 30
    - 30
    description: Week day selection
  - name: DT
    bit_range:
    - 29
    - 28
    description: Date tens in BCD format
  - name: DU
    bit_range:
    - 27
    - 24
    description: Date units or day in BCD format
  - name: MSK3
    bit_range:
    - 23
    - 23
    description: Alarm B hours mask
  - name: PM
    bit_range:
    - 22
    - 22
    description: AM/PM notation
  - name: HT
    bit_range:
    - 21
    - 20
    description: Hour tens in BCD format
  - name: HU
    bit_range:
    - 19
    - 16
    description: Hour units in BCD format
  - name: MSK2
    bit_range:
    - 15
    - 15
    description: Alarm B minutes mask
  - name: MNT
    bit_range:
    - 14
    - 12
    description: Minute tens in BCD format
  - name: MNU
    bit_range:
    - 11
    - 8
    description: Minute units in BCD format
  - name: MSK1
    bit_range:
    - 7
    - 7
    description: Alarm B seconds mask
  - name: ST
    bit_range:
    - 6
    - 4
    description: Second tens in BCD format
  - name: SU
    bit_range:
    - 3
    - 0
    description: Second units in BCD format
  side_effects: null
- id: WPR
  address_offset: 36
  size: 32
  access: WRITE_ONLY
  reset_value: 0
  fields:
  - name: KEY
    bit_range:
    - 7
    - 0
    description: Write protection key
  side_effects: null
- id: SSR
  address_offset: 40
  size: 32
  access: READ_ONLY
  reset_value: 0
  fields:
  - name: SS
    bit_range:
    - 15
    - 0
    description: Sub second value
  side_effects: null
- id: SHIFTR
  address_offset: 44
  size: 32
  access: WRITE_ONLY
  reset_value: 0
  fields:
  - name: ADD1S
    bit_range:
    - 31
    - 31
    description: Add one second
  - name: SUBFS
    bit_range:
    - 14
    - 0
    description: Subtract a fraction of a second
  side_effects: null
- id: TSTR
  address_offset: 48
  size: 32
  access: READ_ONLY
  reset_value: 0
  fields:
  - name: PM
    bit_range:
    - 22
    - 22
    description: AM/PM notation
  - name: HT
    bit_range:
    - 21
    - 20
    description: Hour tens in BCD format
  - name: HU
    bit_range:
    - 19
    - 16
    description: Hour units in BCD format
  - name: MNT
    bit_range:
    - 14
    - 12
    description: Minute tens in BCD format
  - name: MNU
    bit_range:
    - 11
    - 8
    description: Minute units in BCD format
  - name: ST
    bit_range:
    - 6
    - 4
    description: Second tens in BCD format
  - name: SU
    bit_range:
    - 3
    - 0
    description: Second units in BCD format
  side_effects: null
- id: TSDR
  address_offset: 52
  size: 32
  access: READ_ONLY
  reset_value: 0
  fields:
  - name: WDU
    bit_range:
    - 15
    - 13
    description: Week day units
  - name: MT
    bit_range:
    - 12
    - 12
    description: Month tens in BCD format
  - name: MU
    bit_range:
    - 11
    - 8
    description: Month units in BCD format
  - name: DT
    bit_range:
    - 5
    - 4
    description: Date tens in BCD format
  - name: DU
    bit_range:
    - 3
    - 0
    description: Date units in BCD format
  side_effects: null
- id: TSSSR
  address_offset: 56
  size: 32
  access: READ_ONLY
  reset_value: 0
  fields:
  - name: SS
    bit_range:
    - 15
    - 0
    description: Sub second value
  side_effects: null
- id: CALR
  address_offset: 60
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: CALP
    bit_range:
    - 15
    - 15
    description: Increase frequency of RTC by 488.5 ppm
  - name: CALW8
    bit_range:
    - 14
    - 14
    description: Use an 8-second calibration cycle period
  - name: CALW16
    bit_range:
    - 13
    - 13
    description: Use a 16-second calibration cycle period
  - name: CALM
    bit_range:
    - 8
    - 0
    description: Calibration minus
  side_effects: null
- id: TAFCR
  address_offset: 64
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: ALARMOUTTYPE
    bit_range:
    - 18
    - 18
    description: AFO_ALARM output type
  - name: TSINSEL
    bit_range:
    - 17
    - 17
    description: TIMESTAMP mapping
  - name: TAMP1INSEL
    bit_range:
    - 16
    - 16
    description: TAMPER1 mapping
  - name: TAMPPUDIS
    bit_range:
    - 15
    - 15
    description: TAMPER pull-up disable
  - name: TAMPPRCH
    bit_range:
    - 14
    - 13
    description: Tamper precharge duration
  - name: TAMPFLT
    bit_range:
    - 12
    - 11
    description: Tamper filter count
  - name: TAMPFREQ
    bit_range:
    - 10
    - 8
    description: Tamper sampling frequency
  - name: TAMPTS
    bit_range:
    - 7
    - 7
    description: Activate timestamp on tamper detection event
  - name: TAMP2TRG
    bit_range:
    - 4
    - 4
    description: Active level for tamper 2
  - name: TAMP2E
    bit_range:
    - 3
    - 3
    description: Tamper 2 detection enable
  - name: TAMPIE
    bit_range:
    - 2
    - 2
    description: Tamper interrupt enable
  - name: TAMP1TRG
    bit_range:
    - 1
    - 1
    description: Active level for tamper 1
  - name: TAMP1E
    bit_range:
    - 0
    - 0
    description: Tamper 1 detection enable
  side_effects: null
- id: ALRMASSR
  address_offset: 68
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: MASKSS
    bit_range:
    - 27
    - 24
    description: Mask the most-significant bits starting at this bit
  - name: SS
    bit_range:
    - 14
    - 0
    description: Sub seconds value
  side_effects: null
- id: ALRMBSSR
  address_offset: 72
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: MASKSS
    bit_range:
    - 27
    - 24
    description: Mask the most-significant bits starting at this bit
  - name: SS
    bit_range:
    - 14
    - 0
    description: Sub seconds value
  side_effects: null
- id: BKP0R
  address_offset: 80
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: BKP
    bit_range:
    - 31
    - 0
    description: BKP
  side_effects: null
- id: BKP1R
  address_offset: 84
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: BKP
    bit_range:
    - 31
    - 0
    description: BKP
  side_effects: null
- id: BKP2R
  address_offset: 88
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: BKP
    bit_range:
    - 31
    - 0
    description: BKP
  side_effects: null
- id: BKP3R
  address_offset: 92
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: BKP
    bit_range:
    - 31
    - 0
    description: BKP
  side_effects: null
- id: BKP4R
  address_offset: 96
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: BKP
    bit_range:
    - 31
    - 0
    description: BKP
  side_effects: null
- id: BKP5R
  address_offset: 100
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: BKP
    bit_range:
    - 31
    - 0
    description: BKP
  side_effects: null
- id: BKP6R
  address_offset: 104
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: BKP
    bit_range:
    - 31
    - 0
    description: BKP
  side_effects: null
- id: BKP7R
  address_offset: 108
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: BKP
    bit_range:
    - 31
    - 0
    description: BKP
  side_effects: null
- id: BKP8R
  address_offset: 112
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: BKP
    bit_range:
    - 31
    - 0
    description: BKP
  side_effects: null
- id: BKP9R
  address_offset: 116
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: BKP
    bit_range:
    - 31
    - 0
    description: BKP
  side_effects: null
- id: BKP10R
  address_offset: 120
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: BKP
    bit_range:
    - 31
    - 0
    description: BKP
  side_effects: null
- id: BKP11R
  address_offset: 124
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: BKP
    bit_range:
    - 31
    - 0
    description: BKP
  side_effects: null
- id: BKP12R
  address_offset: 128
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: BKP
    bit_range:
    - 31
    - 0
    description: BKP
  side_effects: null
- id: BKP13R
  address_offset: 132
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: BKP
    bit_range:
    - 31
    - 0
    description: BKP
  side_effects: null
- id: BKP14R
  address_offset: 136
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: BKP
    bit_range:
    - 31
    - 0
    description: BKP
  side_effects: null
- id: BKP15R
  address_offset: 140
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: BKP
    bit_range:
    - 31
    - 0
    description: BKP
  side_effects: null
- id: BKP16R
  address_offset: 144
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: BKP
    bit_range:
    - 31
    - 0
    description: BKP
  side_effects: null
- id: BKP17R
  address_offset: 148
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: BKP
    bit_range:
    - 31
    - 0
    description: BKP
  side_effects: null
- id: BKP18R
  address_offset: 152
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: BKP
    bit_range:
    - 31
    - 0
    description: BKP
  side_effects: null
- id: BKP19R
  address_offset: 156
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: BKP
    bit_range:
    - 31
    - 0
    description: BKP
  side_effects: null
interrupts:
  EXTI22_RTC_WKUP: 3
  EXTI17_RTC_Alarm: 41
timing: null
