peripheral: SCB
version: 0.1.0
registers:
- id: CPUID
  address_offset: 0
  size: 32
  access: READ_ONLY
  reset_value: 1091551809
  fields:
  - name: Revision
    bit_range:
    - 3
    - 0
    description: Revision number
  - name: PartNo
    bit_range:
    - 15
    - 4
    description: |-
      Part number of the
                    processor
  - name: Constant
    bit_range:
    - 19
    - 16
    description: Reads as 0xF
  - name: Variant
    bit_range:
    - 23
    - 20
    description: Variant number
  - name: Implementer
    bit_range:
    - 31
    - 24
    description: Implementer code
  side_effects: null
- id: ICSR
  address_offset: 4
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: VECTACTIVE
    bit_range:
    - 8
    - 0
    description: Active vector
  - name: RETTOBASE
    bit_range:
    - 11
    - 11
    description: Return to base level
  - name: VECTPENDING
    bit_range:
    - 18
    - 12
    description: Pending vector
  - name: ISRPENDING
    bit_range:
    - 22
    - 22
    description: Interrupt pending flag
  - name: PENDSTCLR
    bit_range:
    - 25
    - 25
    description: |-
      SysTick exception clear-pending
                    bit
  - name: PENDSTSET
    bit_range:
    - 26
    - 26
    description: |-
      SysTick exception set-pending
                    bit
  - name: PENDSVCLR
    bit_range:
    - 27
    - 27
    description: PendSV clear-pending bit
  - name: PENDSVSET
    bit_range:
    - 28
    - 28
    description: PendSV set-pending bit
  - name: NMIPENDSET
    bit_range:
    - 31
    - 31
    description: NMI set-pending bit.
  side_effects: null
- id: VTOR
  address_offset: 8
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: TBLOFF
    bit_range:
    - 29
    - 9
    description: |-
      Vector table base offset
                    field
  side_effects: null
- id: AIRCR
  address_offset: 12
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: VECTRESET
    bit_range:
    - 0
    - 0
    description: VECTRESET
  - name: VECTCLRACTIVE
    bit_range:
    - 1
    - 1
    description: VECTCLRACTIVE
  - name: SYSRESETREQ
    bit_range:
    - 2
    - 2
    description: SYSRESETREQ
  - name: PRIGROUP
    bit_range:
    - 10
    - 8
    description: PRIGROUP
  - name: ENDIANESS
    bit_range:
    - 15
    - 15
    description: ENDIANESS
  - name: VECTKEYSTAT
    bit_range:
    - 31
    - 16
    description: Register key
  side_effects: null
- id: SCR
  address_offset: 16
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: SLEEPONEXIT
    bit_range:
    - 1
    - 1
    description: SLEEPONEXIT
  - name: SLEEPDEEP
    bit_range:
    - 2
    - 2
    description: SLEEPDEEP
  - name: SEVEONPEND
    bit_range:
    - 4
    - 4
    description: Send Event on Pending bit
  side_effects: null
- id: CCR
  address_offset: 20
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: NONBASETHRDENA
    bit_range:
    - 0
    - 0
    description: |-
      Configures how the processor enters
                    Thread mode
  - name: USERSETMPEND
    bit_range:
    - 1
    - 1
    description: USERSETMPEND
  - name: UNALIGN__TRP
    bit_range:
    - 3
    - 3
    description: UNALIGN_ TRP
  - name: DIV_0_TRP
    bit_range:
    - 4
    - 4
    description: DIV_0_TRP
  - name: BFHFNMIGN
    bit_range:
    - 8
    - 8
    description: BFHFNMIGN
  - name: STKALIGN
    bit_range:
    - 9
    - 9
    description: STKALIGN
  side_effects: null
- id: SHPR1
  address_offset: 24
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: PRI_4
    bit_range:
    - 7
    - 0
    description: |-
      Priority of system handler
                    4
  - name: PRI_5
    bit_range:
    - 15
    - 8
    description: |-
      Priority of system handler
                    5
  - name: PRI_6
    bit_range:
    - 23
    - 16
    description: |-
      Priority of system handler
                    6
  side_effects: null
- id: SHPR2
  address_offset: 28
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: PRI_11
    bit_range:
    - 31
    - 24
    description: |-
      Priority of system handler
                    11
  side_effects: null
- id: SHPR3
  address_offset: 32
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: PRI_14
    bit_range:
    - 23
    - 16
    description: |-
      Priority of system handler
                    14
  - name: PRI_15
    bit_range:
    - 31
    - 24
    description: |-
      Priority of system handler
                    15
  side_effects: null
- id: SHCRS
  address_offset: 36
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: MEMFAULTACT
    bit_range:
    - 0
    - 0
    description: |-
      Memory management fault exception active
                    bit
  - name: BUSFAULTACT
    bit_range:
    - 1
    - 1
    description: |-
      Bus fault exception active
                    bit
  - name: USGFAULTACT
    bit_range:
    - 3
    - 3
    description: |-
      Usage fault exception active
                    bit
  - name: SVCALLACT
    bit_range:
    - 7
    - 7
    description: SVC call active bit
  - name: MONITORACT
    bit_range:
    - 8
    - 8
    description: Debug monitor active bit
  - name: PENDSVACT
    bit_range:
    - 10
    - 10
    description: |-
      PendSV exception active
                    bit
  - name: SYSTICKACT
    bit_range:
    - 11
    - 11
    description: |-
      SysTick exception active
                    bit
  - name: USGFAULTPENDED
    bit_range:
    - 12
    - 12
    description: |-
      Usage fault exception pending
                    bit
  - name: MEMFAULTPENDED
    bit_range:
    - 13
    - 13
    description: |-
      Memory management fault exception
                    pending bit
  - name: BUSFAULTPENDED
    bit_range:
    - 14
    - 14
    description: |-
      Bus fault exception pending
                    bit
  - name: SVCALLPENDED
    bit_range:
    - 15
    - 15
    description: SVC call pending bit
  - name: MEMFAULTENA
    bit_range:
    - 16
    - 16
    description: |-
      Memory management fault enable
                    bit
  - name: BUSFAULTENA
    bit_range:
    - 17
    - 17
    description: Bus fault enable bit
  - name: USGFAULTENA
    bit_range:
    - 18
    - 18
    description: Usage fault enable bit
  side_effects: null
- id: CFSR_UFSR_BFSR_MMFSR
  address_offset: 40
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: IACCVIOL
    bit_range:
    - 1
    - 1
    description: |-
      Instruction access violation
                    flag
  - name: MUNSTKERR
    bit_range:
    - 3
    - 3
    description: |-
      Memory manager fault on unstacking for a
                    return from exception
  - name: MSTKERR
    bit_range:
    - 4
    - 4
    description: |-
      Memory manager fault on stacking for
                    exception entry.
  - name: MLSPERR
    bit_range:
    - 5
    - 5
    description: MLSPERR
  - name: MMARVALID
    bit_range:
    - 7
    - 7
    description: |-
      Memory Management Fault Address Register
                    (MMAR) valid flag
  - name: IBUSERR
    bit_range:
    - 8
    - 8
    description: Instruction bus error
  - name: PRECISERR
    bit_range:
    - 9
    - 9
    description: Precise data bus error
  - name: IMPRECISERR
    bit_range:
    - 10
    - 10
    description: Imprecise data bus error
  - name: UNSTKERR
    bit_range:
    - 11
    - 11
    description: |-
      Bus fault on unstacking for a return
                    from exception
  - name: STKERR
    bit_range:
    - 12
    - 12
    description: |-
      Bus fault on stacking for exception
                    entry
  - name: LSPERR
    bit_range:
    - 13
    - 13
    description: |-
      Bus fault on floating-point lazy state
                    preservation
  - name: BFARVALID
    bit_range:
    - 15
    - 15
    description: |-
      Bus Fault Address Register (BFAR) valid
                    flag
  - name: UNDEFINSTR
    bit_range:
    - 16
    - 16
    description: |-
      Undefined instruction usage
                    fault
  - name: INVSTATE
    bit_range:
    - 17
    - 17
    description: Invalid state usage fault
  - name: INVPC
    bit_range:
    - 18
    - 18
    description: |-
      Invalid PC load usage
                    fault
  - name: NOCP
    bit_range:
    - 19
    - 19
    description: |-
      No coprocessor usage
                    fault.
  - name: UNALIGNED
    bit_range:
    - 24
    - 24
    description: |-
      Unaligned access usage
                    fault
  - name: DIVBYZERO
    bit_range:
    - 25
    - 25
    description: Divide by zero usage fault
  side_effects: null
- id: HFSR
  address_offset: 44
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: VECTTBL
    bit_range:
    - 1
    - 1
    description: Vector table hard fault
  - name: FORCED
    bit_range:
    - 30
    - 30
    description: Forced hard fault
  - name: DEBUG_VT
    bit_range:
    - 31
    - 31
    description: Reserved for Debug use
  side_effects: null
- id: MMFAR
  address_offset: 52
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: MMFAR
    bit_range:
    - 31
    - 0
    description: |-
      Memory management fault
                    address
  side_effects: null
- id: BFAR
  address_offset: 56
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: BFAR
    bit_range:
    - 31
    - 0
    description: Bus fault address
  side_effects: null
- id: AFSR
  address_offset: 60
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: IMPDEF
    bit_range:
    - 31
    - 0
    description: Implementation defined
  side_effects: null
interrupts: null
timing: null
