peripheral: TIM17
version: 0.1.0
registers:
- id: CR1
  address_offset: 0
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: CEN
    bit_range:
    - 0
    - 0
    description: Counter enable
  - name: UDIS
    bit_range:
    - 1
    - 1
    description: Update disable
  - name: URS
    bit_range:
    - 2
    - 2
    description: Update request source
  - name: OPM
    bit_range:
    - 3
    - 3
    description: One-pulse mode
  - name: ARPE
    bit_range:
    - 7
    - 7
    description: Auto-reload preload enable
  - name: CKD
    bit_range:
    - 9
    - 8
    description: Clock division
  - name: UIFREMAP
    bit_range:
    - 11
    - 11
    description: UIF status bit remapping
  side_effects: null
- id: CR2
  address_offset: 4
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: CCPC
    bit_range:
    - 0
    - 0
    description: |-
      Capture/compare preloaded
                    control
  - name: CCUS
    bit_range:
    - 2
    - 2
    description: |-
      Capture/compare control update
                    selection
  - name: CCDS
    bit_range:
    - 3
    - 3
    description: |-
      Capture/compare DMA
                    selection
  - name: OIS1
    bit_range:
    - 8
    - 8
    description: Output Idle state 1
  - name: OIS1N
    bit_range:
    - 9
    - 9
    description: Output Idle state 1
  side_effects: null
- id: DIER
  address_offset: 12
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: UIE
    bit_range:
    - 0
    - 0
    description: Update interrupt enable
  - name: CC1IE
    bit_range:
    - 1
    - 1
    description: |-
      Capture/Compare 1 interrupt
                    enable
  - name: COMIE
    bit_range:
    - 5
    - 5
    description: COM interrupt enable
  - name: TIE
    bit_range:
    - 6
    - 6
    description: Trigger interrupt enable
  - name: BIE
    bit_range:
    - 7
    - 7
    description: Break interrupt enable
  - name: UDE
    bit_range:
    - 8
    - 8
    description: Update DMA request enable
  - name: CC1DE
    bit_range:
    - 9
    - 9
    description: |-
      Capture/Compare 1 DMA request
                    enable
  - name: COMDE
    bit_range:
    - 13
    - 13
    description: COM DMA request enable
  - name: TDE
    bit_range:
    - 14
    - 14
    description: Trigger DMA request enable
  side_effects: null
- id: SR
  address_offset: 16
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: UIF
    bit_range:
    - 0
    - 0
    description: Update interrupt flag
  - name: CC1IF
    bit_range:
    - 1
    - 1
    description: |-
      Capture/compare 1 interrupt
                    flag
  - name: COMIF
    bit_range:
    - 5
    - 5
    description: COM interrupt flag
  - name: TIF
    bit_range:
    - 6
    - 6
    description: Trigger interrupt flag
  - name: BIF
    bit_range:
    - 7
    - 7
    description: Break interrupt flag
  - name: CC1OF
    bit_range:
    - 9
    - 9
    description: |-
      Capture/Compare 1 overcapture
                    flag
  side_effects: null
- id: EGR
  address_offset: 20
  size: 32
  access: WRITE_ONLY
  reset_value: 0
  fields:
  - name: UG
    bit_range:
    - 0
    - 0
    description: Update generation
  - name: CC1G
    bit_range:
    - 1
    - 1
    description: |-
      Capture/compare 1
                    generation
  - name: COMG
    bit_range:
    - 5
    - 5
    description: |-
      Capture/Compare control update
                    generation
  - name: TG
    bit_range:
    - 6
    - 6
    description: Trigger generation
  - name: BG
    bit_range:
    - 7
    - 7
    description: Break generation
  side_effects: null
- id: CCMR1_Input
  address_offset: 24
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: CC1S
    bit_range:
    - 1
    - 0
    description: |-
      Capture/Compare 1
                    selection
  - name: IC1PSC
    bit_range:
    - 3
    - 2
    description: Input capture 1 prescaler
  - name: IC1F
    bit_range:
    - 7
    - 4
    description: Input capture 1 filter
  side_effects: null
- id: CCMR1_Output
  address_offset: 24
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: CC1S
    bit_range:
    - 1
    - 0
    description: |-
      Capture/Compare 1
                    selection
  - name: OC1FE
    bit_range:
    - 2
    - 2
    description: |-
      Output Compare 1 fast
                    enable
  - name: OC1PE
    bit_range:
    - 3
    - 3
    description: |-
      Output Compare 1 preload
                    enable
  - name: OC1M
    bit_range:
    - 6
    - 4
    description: Output Compare 1 mode
  - name: OC1M_2
    bit_range:
    - 16
    - 16
    description: Output Compare 1 mode
  side_effects: null
- id: CCER
  address_offset: 32
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: CC1E
    bit_range:
    - 0
    - 0
    description: |-
      Capture/Compare 1 output
                    enable
  - name: CC1P
    bit_range:
    - 1
    - 1
    description: |-
      Capture/Compare 1 output
                    Polarity
  - name: CC1NE
    bit_range:
    - 2
    - 2
    description: |-
      Capture/Compare 1 complementary output
                    enable
  - name: CC1NP
    bit_range:
    - 3
    - 3
    description: |-
      Capture/Compare 1 output
                    Polarity
  side_effects: null
- id: CNT
  address_offset: 36
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: CNT
    bit_range:
    - 15
    - 0
    description: counter value
  - name: UIFCPY
    bit_range:
    - 31
    - 31
    description: UIF Copy
  side_effects: null
- id: PSC
  address_offset: 40
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: PSC
    bit_range:
    - 15
    - 0
    description: Prescaler value
  side_effects: null
- id: ARR
  address_offset: 44
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: ARR
    bit_range:
    - 15
    - 0
    description: Auto-reload value
  side_effects: null
- id: RCR
  address_offset: 48
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: REP
    bit_range:
    - 7
    - 0
    description: Repetition counter value
  side_effects: null
- id: CCR1
  address_offset: 52
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: CCR1
    bit_range:
    - 15
    - 0
    description: Capture/Compare 1 value
  side_effects: null
- id: BDTR
  address_offset: 68
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: DTG
    bit_range:
    - 7
    - 0
    description: Dead-time generator setup
  - name: LOCK
    bit_range:
    - 9
    - 8
    description: Lock configuration
  - name: OSSI
    bit_range:
    - 10
    - 10
    description: |-
      Off-state selection for Idle
                    mode
  - name: OSSR
    bit_range:
    - 11
    - 11
    description: |-
      Off-state selection for Run
                    mode
  - name: BKE
    bit_range:
    - 12
    - 12
    description: Break enable
  - name: BKP
    bit_range:
    - 13
    - 13
    description: Break polarity
  - name: AOE
    bit_range:
    - 14
    - 14
    description: Automatic output enable
  - name: MOE
    bit_range:
    - 15
    - 15
    description: Main output enable
  - name: BKF
    bit_range:
    - 19
    - 16
    description: Break filter
  side_effects: null
- id: DCR
  address_offset: 72
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: DBA
    bit_range:
    - 4
    - 0
    description: DMA base address
  - name: DBL
    bit_range:
    - 12
    - 8
    description: DMA burst length
  side_effects: null
- id: DMAR
  address_offset: 76
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: DMAB
    bit_range:
    - 15
    - 0
    description: |-
      DMA register for burst
                    accesses
  side_effects: null
- id: OR1
  address_offset: 80
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: TI1_RMP
    bit_range:
    - 1
    - 0
    description: Input capture 1 remap
  side_effects: null
- id: OR2
  address_offset: 96
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: BKINE
    bit_range:
    - 0
    - 0
    description: BRK BKIN input enable
  - name: BKCMP1E
    bit_range:
    - 1
    - 1
    description: BRK COMP1 enable
  - name: BKCMP2E
    bit_range:
    - 2
    - 2
    description: BRK COMP2 enable
  - name: BKDFBK1E
    bit_range:
    - 8
    - 8
    description: BRK DFSDM_BREAK1 enable
  - name: BKINP
    bit_range:
    - 9
    - 9
    description: BRK BKIN input polarity
  - name: BKCMP1P
    bit_range:
    - 10
    - 10
    description: BRK COMP1 input polarity
  - name: BKCMP2P
    bit_range:
    - 11
    - 11
    description: BRK COMP2 input polarit
  side_effects: null
interrupts: null
timing: null
