peripheral: SCB_ACTRL
version: 0.1.0
registers:
- id: ACTRL
  address_offset: 0
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: DISMCYCINT
    bit_range:
    - 0
    - 0
    description: DISMCYCINT
  - name: DISDEFWBUF
    bit_range:
    - 1
    - 1
    description: DISDEFWBUF
  - name: DISFOLD
    bit_range:
    - 2
    - 2
    description: DISFOLD
  - name: DISFPCA
    bit_range:
    - 8
    - 8
    description: DISFPCA
  - name: DISOOFP
    bit_range:
    - 9
    - 9
    description: DISOOFP
  side_effects: null
interrupts: null
timing: null
