peripheral: RNG
version: 0.1.0
registers:
- id: CR
  address_offset: 0
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: RNGEN
    bit_range:
    - 2
    - 2
    description: |-
      Random number generator
                    enable
  - name: IE
    bit_range:
    - 3
    - 3
    description: Interrupt enable
  side_effects: null
- id: SR
  address_offset: 4
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: DRDY
    bit_range:
    - 0
    - 0
    description: Data ready
  - name: CECS
    bit_range:
    - 1
    - 1
    description: Clock error current status
  - name: SECS
    bit_range:
    - 2
    - 2
    description: Seed error current status
  - name: CEIS
    bit_range:
    - 5
    - 5
    description: |-
      Clock error interrupt
                    status
  - name: SEIS
    bit_range:
    - 6
    - 6
    description: |-
      Seed error interrupt
                    status
  side_effects: null
- id: DR
  address_offset: 8
  size: 32
  access: READ_ONLY
  reset_value: 0
  fields:
  - name: RNDATA
    bit_range:
    - 31
    - 0
    description: Random data
  side_effects: null
interrupts: null
timing: null
