peripheral: SYSCFG_COMP
version: 0.1.0
registers:
- id: CFGR1
  address_offset: 0
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: MEM_MODE
    bit_range:
    - 1
    - 0
    description: |-
      Memory mapping selection
                    bits
  - name: BOOT_MODE
    bit_range:
    - 9
    - 8
    description: |-
      Boot mode selected by the boot pins
                    status bits
  side_effects: null
- id: CFGR2
  address_offset: 4
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: FWDISEN
    bit_range:
    - 0
    - 0
    description: Firewall disable bit
  - name: I2C_PB6_FMP
    bit_range:
    - 8
    - 8
    description: |-
      Fm+ drive capability on PB6 enable
                    bit
  - name: I2C_PB7_FMP
    bit_range:
    - 9
    - 9
    description: |-
      Fm+ drive capability on PB7 enable
                    bit
  - name: I2C_PB8_FMP
    bit_range:
    - 10
    - 10
    description: |-
      Fm+ drive capability on PB8 enable
                    bit
  - name: I2C_PB9_FMP
    bit_range:
    - 11
    - 11
    description: |-
      Fm+ drive capability on PB9 enable
                    bit
  - name: I2C1_FMP
    bit_range:
    - 12
    - 12
    description: |-
      I2C1 Fm+ drive capability enable
                    bit
  - name: I2C2_FMP
    bit_range:
    - 13
    - 13
    description: |-
      I2C2 Fm+ drive capability enable
                    bit
  side_effects: null
- id: EXTICR1
  address_offset: 8
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: EXTI0
    bit_range:
    - 3
    - 0
    description: |-
      EXTI x configuration (x = 0 to
                    3)
  - name: EXTI1
    bit_range:
    - 7
    - 4
    description: |-
      EXTI x configuration (x = 0 to
                    3)
  - name: EXTI2
    bit_range:
    - 11
    - 8
    description: |-
      EXTI x configuration (x = 0 to
                    3)
  - name: EXTI3
    bit_range:
    - 15
    - 12
    description: |-
      EXTI x configuration (x = 0 to
                    3)
  side_effects: null
- id: EXTICR2
  address_offset: 12
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: EXTI4
    bit_range:
    - 3
    - 0
    description: |-
      EXTI x configuration (x = 4 to
                    7)
  - name: EXTI5
    bit_range:
    - 7
    - 4
    description: |-
      EXTI x configuration (x = 4 to
                    7)
  - name: EXTI6
    bit_range:
    - 11
    - 8
    description: |-
      EXTI x configuration (x = 4 to
                    7)
  - name: EXTI7
    bit_range:
    - 15
    - 12
    description: |-
      EXTI x configuration (x = 4 to
                    7)
  side_effects: null
- id: EXTICR3
  address_offset: 16
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: EXTI8
    bit_range:
    - 3
    - 0
    description: |-
      EXTI x configuration (x = 8 to
                    11)
  - name: EXTI9
    bit_range:
    - 7
    - 4
    description: |-
      EXTI x configuration (x = 8 to
                    11)
  - name: EXTI10
    bit_range:
    - 11
    - 8
    description: EXTI10
  - name: EXTI11
    bit_range:
    - 15
    - 12
    description: |-
      EXTI x configuration (x = 8 to
                    11)
  side_effects: null
- id: EXTICR4
  address_offset: 20
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: EXTI12
    bit_range:
    - 3
    - 0
    description: EXTI12
  - name: EXTI13
    bit_range:
    - 7
    - 4
    description: EXTI13
  - name: EXTI14
    bit_range:
    - 11
    - 8
    description: EXTI14
  - name: EXTI15
    bit_range:
    - 15
    - 12
    description: |-
      EXTI x configuration (x = 12 to
                    15)
  side_effects: null
- id: COMP1_CSR
  address_offset: 24
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: COMP1EN
    bit_range:
    - 0
    - 0
    description: Comparator 1 enable bit
  - name: COMP1INNSEL
    bit_range:
    - 5
    - 4
    description: |-
      Comparator 1 Input Minus connection
                    configuration bit
  - name: COMP1WM
    bit_range:
    - 8
    - 8
    description: |-
      Comparator 1 window mode selection
                    bit
  - name: COMP1LPTIMIN1
    bit_range:
    - 12
    - 12
    description: |-
      Comparator 1 LPTIM input propagation
                    bit
  - name: COMP1POLARITY
    bit_range:
    - 15
    - 15
    description: |-
      Comparator 1 polarity selection
                    bit
  - name: COMP1VALUE
    bit_range:
    - 30
    - 30
    description: |-
      Comparator 1 output status
                    bit
  - name: COMP1LOCK
    bit_range:
    - 31
    - 31
    description: |-
      COMP1_CSR register lock
                    bit
  side_effects: null
- id: COMP2_CSR
  address_offset: 28
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: COMP2EN
    bit_range:
    - 0
    - 0
    description: Comparator 2 enable bit
  - name: COMP2SPEED
    bit_range:
    - 3
    - 3
    description: |-
      Comparator 2 power mode selection
                    bit
  - name: COMP2INNSEL
    bit_range:
    - 6
    - 4
    description: |-
      Comparator 2 Input Minus connection
                    configuration bit
  - name: COMP2INPSEL
    bit_range:
    - 10
    - 8
    description: |-
      Comparator 2 Input Plus connection
                    configuration bit
  - name: COMP2LPTIMIN2
    bit_range:
    - 12
    - 12
    description: |-
      Comparator 2 LPTIM input 2 propagation
                    bit
  - name: COMP2LPTIMIN1
    bit_range:
    - 13
    - 13
    description: |-
      Comparator 2 LPTIM input 1 propagation
                    bit
  - name: COMP2POLARITY
    bit_range:
    - 15
    - 15
    description: |-
      Comparator 2 polarity selection
                    bit
  - name: COMP2VALUE
    bit_range:
    - 20
    - 20
    description: |-
      Comparator 2 output status
                    bit
  - name: COMP2LOCK
    bit_range:
    - 31
    - 31
    description: |-
      COMP2_CSR register lock
                    bit
  side_effects: null
- id: CFGR3
  address_offset: 32
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: EN_BGAP
    bit_range:
    - 0
    - 0
    description: Vref Enable bit
  - name: SEL_VREF_OUT
    bit_range:
    - 5
    - 4
    description: BGAP_ADC connection bit
  - name: ENBUF_BGAP_ADC
    bit_range:
    - 8
    - 8
    description: |-
      VREFINT reference for ADC enable
                    bit
  - name: ENBUF_SENSOR_ADC
    bit_range:
    - 9
    - 9
    description: |-
      Sensor reference for ADC enable
                    bit
  - name: ENBUF_VREFINT_COMP
    bit_range:
    - 12
    - 12
    description: |-
      VREFINT reference for comparator 2
                    enable bit
  - name: ENREF_RC48MHz
    bit_range:
    - 13
    - 13
    description: |-
      VREFINT reference for 48 MHz RC
                    oscillator enable bit
  - name: REF_RC48MHz_RDYF
    bit_range:
    - 26
    - 26
    description: |-
      VREFINT for 48 MHz RC oscillator ready
                    flag
  - name: SENSOR_ADC_RDYF
    bit_range:
    - 27
    - 27
    description: Sensor for ADC ready flag
  - name: VREFINT_ADC_RDYF
    bit_range:
    - 28
    - 28
    description: VREFINT for ADC ready flag
  - name: VREFINT_COMP_RDYF
    bit_range:
    - 29
    - 29
    description: |-
      VREFINT for comparator ready
                    flag
  - name: VREFINT_RDYF
    bit_range:
    - 30
    - 30
    description: VREFINT ready flag
  - name: REF_LOCK
    bit_range:
    - 31
    - 31
    description: REF_CTRL lock bit
  side_effects: null
interrupts: null
timing: null
