peripheral: APB_CTRL
version: 0.1.0
registers:
- id: SYSCLK_CONF
  address_offset: 0
  size: 32
  access: READ_WRITE
  reset_value: 8192
  fields:
  - name: PRE_DIV_CNT
    bit_range:
    - 9
    - 0
  - name: CLK_320M_EN
    bit_range:
    - 10
    - 10
  - name: CLK_EN
    bit_range:
    - 11
    - 11
  - name: RST_TICK_CNT
    bit_range:
    - 12
    - 12
  - name: QUICK_CLK_CHNG
    bit_range:
    - 13
    - 13
  side_effects: null
- id: XTAL_TICK_CONF
  address_offset: 4
  size: 32
  access: READ_WRITE
  reset_value: 39
  fields:
  - name: XTAL_TICK_NUM
    bit_range:
    - 7
    - 0
  side_effects: null
- id: PLL_TICK_CONF
  address_offset: 8
  size: 32
  access: READ_WRITE
  reset_value: 79
  fields:
  - name: PLL_TICK_NUM
    bit_range:
    - 7
    - 0
  side_effects: null
- id: CK8M_TICK_CONF
  address_offset: 12
  size: 32
  access: READ_WRITE
  reset_value: 11
  fields:
  - name: CK8M_TICK_NUM
    bit_range:
    - 7
    - 0
  side_effects: null
- id: APB_SARADC_CTRL
  address_offset: 16
  size: 32
  access: READ_WRITE
  reset_value: 8356416
  fields:
  - name: SARADC_START_FORCE
    bit_range:
    - 0
    - 0
  - name: SARADC_START
    bit_range:
    - 1
    - 1
  - name: SARADC_SAR2_MUX
    bit_range:
    - 2
    - 2
    description: '1: SAR ADC2 is controlled by DIG ADC2 CTRL  0: SAR ADC2 is controlled by PWDET CTRL'
  - name: SARADC_WORK_MODE
    bit_range:
    - 4
    - 3
    description: '0: single mode  1: double mode  2: alternate mode'
  - name: SARADC_SAR_SEL
    bit_range:
    - 5
    - 5
    description: '0: SAR1  1: SAR2  only work for single SAR mode'
  - name: SARADC_SAR_CLK_GATED
    bit_range:
    - 6
    - 6
  - name: SARADC_SAR_CLK_DIV
    bit_range:
    - 14
    - 7
    description: SAR clock divider
  - name: SARADC_SAR1_PATT_LEN
    bit_range:
    - 18
    - 15
    description: 0 ~ 15 means length 1 ~ 16
  - name: SARADC_SAR2_PATT_LEN
    bit_range:
    - 22
    - 19
    description: 0 ~ 15 means length 1 ~ 16
  - name: SARADC_SAR1_PATT_P_CLEAR
    bit_range:
    - 23
    - 23
    description: clear the pointer of pattern table for DIG ADC1 CTRL
  - name: SARADC_SAR2_PATT_P_CLEAR
    bit_range:
    - 24
    - 24
    description: clear the pointer of pattern table for DIG ADC2 CTRL
  - name: SARADC_DATA_SAR_SEL
    bit_range:
    - 25
    - 25
    description: '1: sar_sel will be coded by the MSB of the 16-bit output data  in this case the resolution should not be larger than 11 bits.'
  - name: SARADC_DATA_TO_I2S
    bit_range:
    - 26
    - 26
    description: '1: I2S input data is from SAR ADC (for DMA)  0: I2S input data is from GPIO matrix'
  side_effects: null
- id: APB_SARADC_CTRL2
  address_offset: 20
  size: 32
  access: READ_WRITE
  reset_value: 510
  fields:
  - name: SARADC_MEAS_NUM_LIMIT
    bit_range:
    - 0
    - 0
  - name: SARADC_MAX_MEAS_NUM
    bit_range:
    - 8
    - 1
    description: max conversion number
  - name: SARADC_SAR1_INV
    bit_range:
    - 9
    - 9
    description: '1: data to DIG ADC1 CTRL is inverted  otherwise not'
  - name: SARADC_SAR2_INV
    bit_range:
    - 10
    - 10
    description: '1: data to DIG ADC2 CTRL is inverted  otherwise not'
  side_effects: null
- id: APB_SARADC_FSM
  address_offset: 24
  size: 32
  access: READ_WRITE
  reset_value: 34144008
  fields:
  - name: SARADC_RSTB_WAIT
    bit_range:
    - 7
    - 0
  - name: SARADC_STANDBY_WAIT
    bit_range:
    - 15
    - 8
  - name: SARADC_START_WAIT
    bit_range:
    - 23
    - 16
  - name: SARADC_SAMPLE_CYCLE
    bit_range:
    - 31
    - 24
    description: sample cycles
  side_effects: null
- id: APB_SARADC_SAR1_PATT_TAB1-4
  address_offset: 28
  size: 32
  access: READ_WRITE
  reset_value: 252645135
  fields:
  - name: SARADC_SAR1_PATT_TAB1
    bit_range:
    - 31
    - 0
    description: item 0 ~ 3 for pattern table 1 (each item one byte)
  side_effects: null
- id: APB_SARADC_SAR2_PATT_TAB1-4
  address_offset: 44
  size: 32
  access: READ_WRITE
  reset_value: 252645135
  fields:
  - name: SARADC_SAR2_PATT_TAB1
    bit_range:
    - 31
    - 0
    description: item 0 ~ 3 for pattern table 2 (each item one byte)
  side_effects: null
- id: APLL_TICK_CONF
  address_offset: 60
  size: 32
  access: READ_WRITE
  reset_value: 99
  fields:
  - name: APLL_TICK_NUM
    bit_range:
    - 7
    - 0
  side_effects: null
- id: DATE
  address_offset: 124
  size: 32
  access: READ_WRITE
  reset_value: 369369088
  fields:
  - name: DATE
    bit_range:
    - 31
    - 0
  side_effects: null
interrupts: null
timing: null
