peripheral: HINF
version: 0.1.0
registers:
- id: CFG_DATA0
  address_offset: 0
  size: 32
  access: READ_WRITE
  reset_value: 572679782
  fields:
  - name: USER_ID_FN1
    bit_range:
    - 15
    - 0
  - name: DEVICE_ID_FN1
    bit_range:
    - 31
    - 16
  side_effects: null
- id: CFG_DATA1
  address_offset: 4
  size: 32
  access: READ_WRITE
  reset_value: 17891345
  fields:
  - name: SDIO_ENABLE
    bit_range:
    - 0
    - 0
  - name: SDIO_IOREADY1
    bit_range:
    - 1
    - 1
  - name: HIGHSPEED_ENABLE
    bit_range:
    - 2
    - 2
  - name: HIGHSPEED_MODE
    bit_range:
    - 3
    - 3
  - name: SDIO_CD_ENABLE
    bit_range:
    - 4
    - 4
  - name: SDIO_IOREADY2
    bit_range:
    - 5
    - 5
  - name: SDIO_INT_MASK
    bit_range:
    - 6
    - 6
  - name: IOENABLE2
    bit_range:
    - 7
    - 7
  - name: CD_DISABLE
    bit_range:
    - 8
    - 8
  - name: FUNC1_EPS
    bit_range:
    - 9
    - 9
  - name: EMP
    bit_range:
    - 10
    - 10
  - name: IOENABLE1
    bit_range:
    - 11
    - 11
  - name: SDIO20_CONF0
    bit_range:
    - 15
    - 12
  - name: SDIO_VER
    bit_range:
    - 27
    - 16
  - name: FUNC2_EPS
    bit_range:
    - 28
    - 28
  - name: SDIO20_CONF1
    bit_range:
    - 31
    - 29
  side_effects: null
- id: CFG_DATA7
  address_offset: 28
  size: 32
  access: READ_WRITE
  reset_value: 131072
  fields:
  - name: PIN_STATE
    bit_range:
    - 7
    - 0
  - name: CHIP_STATE
    bit_range:
    - 15
    - 8
  - name: SDIO_RST
    bit_range:
    - 16
    - 16
  - name: SDIO_IOREADY0
    bit_range:
    - 17
    - 17
  side_effects: null
- id: CIS_CONF0
  address_offset: 32
  size: 32
  access: READ_WRITE
  reset_value: 4294967295
  fields:
  - name: CIS_CONF_W0
    bit_range:
    - 31
    - 0
  side_effects: null
- id: CIS_CONF1
  address_offset: 36
  size: 32
  access: READ_WRITE
  reset_value: 4294967295
  fields:
  - name: CIS_CONF_W1
    bit_range:
    - 31
    - 0
  side_effects: null
- id: CIS_CONF2
  address_offset: 40
  size: 32
  access: READ_WRITE
  reset_value: 4294967295
  fields:
  - name: CIS_CONF_W2
    bit_range:
    - 31
    - 0
  side_effects: null
- id: CIS_CONF3
  address_offset: 44
  size: 32
  access: READ_WRITE
  reset_value: 4294967295
  fields:
  - name: CIS_CONF_W3
    bit_range:
    - 31
    - 0
  side_effects: null
- id: CIS_CONF4
  address_offset: 48
  size: 32
  access: READ_WRITE
  reset_value: 4294967295
  fields:
  - name: CIS_CONF_W4
    bit_range:
    - 31
    - 0
  side_effects: null
- id: CIS_CONF5
  address_offset: 52
  size: 32
  access: READ_WRITE
  reset_value: 4294967295
  fields:
  - name: CIS_CONF_W5
    bit_range:
    - 31
    - 0
  side_effects: null
- id: CIS_CONF6
  address_offset: 56
  size: 32
  access: READ_WRITE
  reset_value: 4294967295
  fields:
  - name: CIS_CONF_W6
    bit_range:
    - 31
    - 0
  side_effects: null
- id: CIS_CONF7
  address_offset: 60
  size: 32
  access: READ_WRITE
  reset_value: 4294967295
  fields:
  - name: CIS_CONF_W7
    bit_range:
    - 31
    - 0
  side_effects: null
- id: CFG_DATA16
  address_offset: 64
  size: 32
  access: READ_WRITE
  reset_value: 859006566
  fields:
  - name: USER_ID_FN2
    bit_range:
    - 15
    - 0
  - name: DEVICE_ID_FN2
    bit_range:
    - 31
    - 16
  side_effects: null
- id: DATE
  address_offset: 252
  size: 32
  access: READ_WRITE
  reset_value: 352518656
  fields:
  - name: SDIO_DATE
    bit_range:
    - 31
    - 0
  side_effects: null
interrupts: null
timing: null
