peripheral: FLASH
version: 0.1.0
registers:
- id: ACR
  address_offset: 0
  size: 32
  access: READ_WRITE
  reset_value: 1536
  fields:
  - name: LATENCY
    bit_range:
    - 3
    - 0
    description: Latency
  - name: PRFTEN
    bit_range:
    - 8
    - 8
    description: Prefetch enable
  - name: ICEN
    bit_range:
    - 9
    - 9
    description: Instruction cache enable
  - name: DCEN
    bit_range:
    - 10
    - 10
    description: Data cache enable
  - name: ICRST
    bit_range:
    - 11
    - 11
    description: Instruction cache reset
  - name: DCRST
    bit_range:
    - 12
    - 12
    description: Data cache reset
  - name: RUN_PD
    bit_range:
    - 13
    - 13
    description: Flash Power-down mode during Low-power               run mode
  - name: SLEEP_PD
    bit_range:
    - 14
    - 14
    description: Flash Power-down mode during Low-power               sleep mode
  - name: DBG_SWEN
    bit_range:
    - 18
    - 18
    description: Debug software enable
  side_effects: null
- id: PDKEYR
  address_offset: 4
  size: 32
  access: WRITE_ONLY
  reset_value: 0
  fields:
  - name: PDKEYR
    bit_range:
    - 31
    - 0
    description: RUN_PD in FLASH_ACR key
  side_effects: null
- id: KEYR
  address_offset: 8
  size: 32
  access: WRITE_ONLY
  reset_value: 0
  fields:
  - name: KEYR
    bit_range:
    - 31
    - 0
    description: KEYR
  side_effects: null
- id: OPTKEYR
  address_offset: 12
  size: 32
  access: WRITE_ONLY
  reset_value: 0
  fields:
  - name: OPTKEYR
    bit_range:
    - 31
    - 0
    description: Option byte key
  side_effects: null
- id: SR
  address_offset: 16
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: EOP
    bit_range:
    - 0
    - 0
    description: End of operation
  - name: OPERR
    bit_range:
    - 1
    - 1
    description: Operation error
  - name: PROGERR
    bit_range:
    - 3
    - 3
    description: Programming error
  - name: WRPERR
    bit_range:
    - 4
    - 4
    description: Write protected error
  - name: PGAERR
    bit_range:
    - 5
    - 5
    description: Programming alignment               error
  - name: SIZERR
    bit_range:
    - 6
    - 6
    description: Size error
  - name: PGSERR
    bit_range:
    - 7
    - 7
    description: Programming sequence error
  - name: MISERR
    bit_range:
    - 8
    - 8
    description: Fast programming data miss               error
  - name: FASTERR
    bit_range:
    - 9
    - 9
    description: Fast programming error
  - name: RDERR
    bit_range:
    - 14
    - 14
    description: PCROP read error
  - name: OPTVERR
    bit_range:
    - 15
    - 15
    description: Option validity error
  - name: BSY
    bit_range:
    - 16
    - 16
    description: Busy
  side_effects: null
- id: CR
  address_offset: 20
  size: 32
  access: READ_WRITE
  reset_value: 3221225472
  fields:
  - name: PG
    bit_range:
    - 0
    - 0
    description: Programming
  - name: PER
    bit_range:
    - 1
    - 1
    description: Page erase
  - name: MER1
    bit_range:
    - 2
    - 2
    description: Bank 1 Mass erase
  - name: PNB
    bit_range:
    - 9
    - 3
    description: Page number
  - name: STRT
    bit_range:
    - 16
    - 16
    description: Start
  - name: OPTSTRT
    bit_range:
    - 17
    - 17
    description: Options modification start
  - name: FSTPG
    bit_range:
    - 18
    - 18
    description: Fast programming
  - name: EOPIE
    bit_range:
    - 24
    - 24
    description: End of operation interrupt               enable
  - name: ERRIE
    bit_range:
    - 25
    - 25
    description: Error interrupt enable
  - name: RDERRIE
    bit_range:
    - 26
    - 26
    description: PCROP read error interrupt               enable
  - name: OBL_LAUNCH
    bit_range:
    - 27
    - 27
    description: Force the option byte               loading
  - name: SEC_PROT1
    bit_range:
    - 28
    - 28
    description: SEC_PROT1
  - name: OPTLOCK
    bit_range:
    - 30
    - 30
    description: Options Lock
  - name: LOCK
    bit_range:
    - 31
    - 31
    description: FLASH_CR Lock
  side_effects: null
- id: ECCR
  address_offset: 24
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: ADDR_ECC
    bit_range:
    - 18
    - 0
    description: ECC fail address
  - name: BK_ECC
    bit_range:
    - 21
    - 21
    description: BK_ECC
  - name: SYSF_ECC
    bit_range:
    - 22
    - 22
    description: SYSF_ECC
  - name: ECCIE
    bit_range:
    - 24
    - 24
    description: ECCIE
  - name: ECCC2
    bit_range:
    - 28
    - 28
    description: ECC correction
  - name: ECCD2
    bit_range:
    - 29
    - 29
    description: ECC2 detection
  - name: ECCC
    bit_range:
    - 30
    - 30
    description: ECC correction
  - name: ECCD
    bit_range:
    - 31
    - 31
    description: ECC detection
  side_effects: null
- id: OPTR
  address_offset: 32
  size: 32
  access: READ_WRITE
  reset_value: 4026531840
  fields:
  - name: RDP
    bit_range:
    - 7
    - 0
    description: Read protection level
  - name: BOR_LEV
    bit_range:
    - 10
    - 8
    description: BOR reset Level
  - name: nRST_STOP
    bit_range:
    - 12
    - 12
    description: nRST_STOP
  - name: nRST_STDBY
    bit_range:
    - 13
    - 13
    description: nRST_STDBY
  - name: nRST_SHDW
    bit_range:
    - 14
    - 14
    description: nRST_SHDW
  - name: IDWG_SW
    bit_range:
    - 16
    - 16
    description: Independent watchdog               selection
  - name: IWDG_STOP
    bit_range:
    - 17
    - 17
    description: Independent watchdog counter freeze in               Stop mode
  - name: IWDG_STDBY
    bit_range:
    - 18
    - 18
    description: Independent watchdog counter freeze in               Standby mode
  - name: WWDG_SW
    bit_range:
    - 19
    - 19
    description: Window watchdog selection
  - name: nBOOT1
    bit_range:
    - 23
    - 23
    description: Boot configuration
  - name: SRAM2_PE
    bit_range:
    - 24
    - 24
    description: SRAM2 parity check enable
  - name: SRAM2_RST
    bit_range:
    - 25
    - 25
    description: SRAM2 Erase when system               reset
  - name: nSWBOOT0
    bit_range:
    - 26
    - 26
    description: nSWBOOT0
  - name: nBOOT0
    bit_range:
    - 27
    - 27
    description: nBOOT0
  - name: NRST_MODE
    bit_range:
    - 29
    - 28
    description: NRST_MODE
  - name: IRHEN
    bit_range:
    - 30
    - 30
    description: IRHEN
  side_effects: null
- id: PCROP1SR
  address_offset: 36
  size: 32
  access: READ_WRITE
  reset_value: 4294901760
  fields:
  - name: PCROP1_STRT
    bit_range:
    - 14
    - 0
    description: Bank 1 PCROP area start               offset
  side_effects: null
- id: PCROP1ER
  address_offset: 40
  size: 32
  access: READ_WRITE
  reset_value: 268369920
  fields:
  - name: PCROP1_END
    bit_range:
    - 14
    - 0
    description: Bank 1 PCROP area end               offset
  - name: PCROP_RDP
    bit_range:
    - 31
    - 31
    description: PCROP area preserved when RDP level               decreased
  side_effects: null
- id: WRP1AR
  address_offset: 44
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: WRP1A_STRT
    bit_range:
    - 6
    - 0
    description: Bank 1 WRP first area start               offset
  - name: WRP1A_END
    bit_range:
    - 22
    - 16
    description: Bank 1 WRP first area A end               offset
  side_effects: null
- id: WRP1BR
  address_offset: 48
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: WRP1B_STRT
    bit_range:
    - 6
    - 0
    description: Bank 1 WRP second area B end               offset
  - name: WRP1B_END
    bit_range:
    - 22
    - 16
    description: Bank 1 WRP second area B start               offset
  side_effects: null
- id: SEC1R
  address_offset: 112
  size: 32
  access: READ_WRITE
  reset_value: 4278255360
  fields:
  - name: SEC_SIZE1
    bit_range:
    - 7
    - 0
    description: SEC_SIZE1
  - name: BOOT_LOCK
    bit_range:
    - 16
    - 16
    description: BOOT_LOCK
  side_effects: null
interrupts:
  FLASH: 4
timing: null
